#minimumReleaseAge: 4320 # Minutes = 3 Days
minimumReleaseAgeExclude:
  - "@rimelight/*"
  - "rimelight-cli"
allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
